requires 'Mojolicious', '>= 7.88';
requires 'Mojolicious::Plugin::Authentication';
requires 'Imager';
requires 'File::Basename';
requires 'File::Path';
requires 'File::Spec';
requires 'Cwd';
requires 'Getopt::Long';
requires 'DBI';
requires 'DBD::SQLite';
requires 'Digest::SHA';